import { CookiePreferencesButton } from "@/components/site/cookie-consent";
import { StaticPageStructuredData } from "@/components/site/structured-data";
import { WHATSAPP_URL } from "@/lib/contact";
import { pageMetadata, seoPages } from "@/lib/seo";

const seo = seoPages["/privacidade"];
export const metadata = pageMetadata("/privacidade", seo.title, seo.description);

export default function PrivacyPage() {
  return <article className="site-container section-space">
    <StaticPageStructuredData path="/privacidade" />
    <div className="max-w-3xl">
      <p className="eyebrow">Transparência / Quintec</p>
      <h1 className="page-title">Privacidade e cookies</h1>
      <p className="mt-6 text-lg leading-relaxed text-muted">Você pode navegar, conhecer os projetos e entrar em contato sem aceitar tecnologias opcionais de estatísticas ou publicidade.</p>
      <p className="mt-4 text-sm text-muted">Atualizada em 12 de setembro de 2026.</p>
      <div className="mt-10 space-y-10 text-muted [&_h2]:mb-4 [&_h2]:text-2xl [&_h2]:font-semibold [&_h2]:text-foreground [&_p]:leading-relaxed [&_a]:underline [&_a]:underline-offset-4">
        <section><h2>Quem cuida dos dados</h2><p>Este site é mantido por Gustavo Quintans, responsável pela Quintec. Para assuntos de privacidade, dúvidas ou solicitações sobre seus dados, fale pelo <a href={WHATSAPP_URL} target="_blank" rel="noopener noreferrer">WhatsApp: (11) 98906-0037</a>.</p></section>
        <section><h2>Quando você entra em contato</h2><p>O formulário usa nome, e-mail, empresa (opcional), solução desejada e descrição do projeto para preparar uma mensagem no seu navegador. Ao continuar, você abre o WhatsApp e decide se quer enviar essa mensagem. O site não envia o conteúdo do formulário para as ferramentas de estatísticas ou publicidade.</p><p className="mt-4">As informações enviadas na conversa são usadas para responder à solicitação, avaliar o projeto e preparar uma proposta. São mantidas pelo tempo necessário ao atendimento, à relação contratual e às obrigações aplicáveis. Você pode solicitar informações sobre a conservação e a exclusão pelo contato acima.</p></section>
        <section><h2>Suas escolhas neste navegador</h2><p>Guardamos suas preferências por 180 dias no armazenamento local do navegador, com a data e a versão da escolha. Esse registro é necessário para respeitar sua decisão e evitar perguntar a cada página. Aceitar e rejeitar têm a mesma duração.</p><p className="mt-4">As opções de estatísticas e publicidade começam desativadas. Navegar ou fechar a janela de preferências não significa aceitar. O aviso reaparece se o prazo terminar, se você limpar os dados do navegador ou se as finalidades mudarem. Quando o navegador impede salvar a escolha, ela pode durar somente esta visita.</p><CookiePreferencesButton /></section>
        <section><h2>Estatísticas e desempenho · opcionais</h2><p>Com sua autorização, a Vercel Web Analytics mede visitas e interações, e o Speed Insights mede o desempenho das páginas. A Vercel informa que o Web Analytics não utiliza cookies de rastreamento e trabalha com estatísticas agregadas. Ainda assim, neste site essas ferramentas dependem da sua escolha de estatísticas.</p><p className="mt-4">Os eventos incluem a página e informações de interação ou desempenho. Removemos parâmetros de consulta e fragmentos das URLs enviadas por essas integrações. Textos livres do formulário não fazem parte dos eventos personalizados. Consulte <a href="https://vercel.com/docs/analytics/privacy-policy" target="_blank" rel="noopener noreferrer">a documentação de privacidade da Vercel</a> e <a href="https://vercel.com/docs/speed-insights/privacy-policy" target="_blank" rel="noopener noreferrer">a política do Speed Insights</a>.</p></section>
        <section><h2>Publicidade · opcional</h2><p>Com sua autorização e quando configurado, o Pixel da Meta registra visitas e ações, como cliques no WhatsApp, para medir campanhas e permitir personalização de anúncios. A Meta pode receber a URL visitada, identificadores de cookies e informações de conexão e do dispositivo, associando esses dados a outros que possui.</p><p className="mt-4">Essa integração pode usar cookies como <code>_fbp</code> e <code>_fbc</code>, cujos prazos são definidos pela Meta e podem ser renovados durante o uso. Ao retirar a autorização, interrompemos novos eventos da integração, comunicamos a revogação ao Pixel e removemos esses cookies quando acessíveis ao nosso domínio. Isso não apaga retroativamente informações já recebidas pela Meta. Saiba mais na <a href="https://www.facebook.com/privacy/policies/cookies/" target="_blank" rel="noopener noreferrer">política de cookies da Meta</a>.</p></section>
        <section><h2>Hospedagem e serviços externos</h2><p>A Vercel hospeda o site e pode tratar registros técnicos de conexão para entregar as páginas, manter a segurança e diagnosticar falhas. Esse funcionamento é separado das ferramentas opcionais de medição. Consulte <a href="https://vercel.com/legal/privacy-notice" target="_blank" rel="noopener noreferrer">a política de privacidade da Vercel</a>.</p><p className="mt-4">Ao abrir WhatsApp, GitHub ou redes sociais, você passa a utilizar serviços com suas próprias políticas. Fornecedores podem processar informações fora do Brasil. Consulte suas políticas para informações sobre locais de processamento, conservação e proteção dos dados.</p></section>
        <section><h2>Como exercer seus direitos</h2><p>Você pode pedir confirmação de tratamento, acesso, correção, informações sobre compartilhamento e, quando cabível, exclusão dos seus dados. Também pode retirar o consentimento para as ferramentas opcionais pelo botão de preferências, sem perder acesso ao site. Para outras solicitações, use o contato de privacidade informado nesta página.</p></section>
      </div>
    </div>
  </article>;
}
